
export const environment = {
  production: false,
  apiTipoCanal: 'http://localhost:3000/api/tipo-canal',
  apiTipoCliente: 'http://localhost:3000/api/tipo-cliente',
  apiTipoCondiciones: 'http://localhost:3000/api/tipo-condiciones',
  apiTipoFamilia: 'http://localhost:3000/api/tipo-familia',
  apiTipoIVA: 'http://localhost:3000/api/tipo-iva',
  apiTipoPermiso: 'http://localhost:3000/api/tipo-permiso',
  apiTipoProducto: 'http://localhost:3000/api/tipo-producto',
  apiTipoRegla: 'http://localhost:3000/api/tipo-reglaComercial',
  apiTipoTelefono: 'http://localhost:3000/api/tipo-telefono',
  apiUsuario: 'http://localhost:3000/api/usuario',
  apiCliente: 'http://localhost:3000/api/cliente',
  apiEmpresa: 'http://localhost:3000/api/empresa',
  apiVendedor: 'http://localhost:3000/api/vendedor',
  apiLocalidad: 'http://localhost:3000/api/localidad',
  apiProvincia: 'http://localhost:3000/api/provincia',
  apiPedido: 'http://localhost:3000/api/pedido',
};
