export const environment = {
  production: false,
  apiTipoCanal: ' http://localhost:3000/api/tipo-canal',
  apiTipoCliente: ' http://localhost:3000/api/tipo-cliente',
  apiTipoCondiciones: ' http://localhost:3000/api/tipo-condiciones',
  apiTipoFamilia: ' http://localhost:3000/api/tipo-familia',
  apiTipoIVA: ' http://localhost:3000/api/tipo-iva',
  apiTipoPermiso: ' http://localhost:3000/api/tipo-permiso',
  apiTipoProducto: ' http://localhost:3000/api/tipo-producto',
  apiTipoRegla: ' http://localhost:3000/api/tipo-reglaComercial',
  apiTipoTelefono: ' http://localhost:3000/api/tipo-telefono',
  apiUsuario: ' http://localhost:3000/api/usuario',
  apiCliente: ' http://localhost:3000/api/cliente',
  apiEmpresa: ' http://localhost:3000/api/empresa',
  apiVendedor: ' http://localhost:3000/api/vendedor',
  apiLocalidad: ' http://localhost:3000/api/localidad',
  apiProvincia: ' http://localhost:3000/api/provincia',
  apiPedido: ' http://localhost:3000/api/pedido',
  apiOperacion: ' http://localhost:3000/api/operacion',
  apiDetallePedido: ' http://localhost:3000/api/detallePedido',
  apiEmail:' http://localhost:3000/api/email',
  apiAccesoPermiso:' http://localhost:3000/api/accesoPermiso',
  apiAcceso:' http://localhost:3000/api/acceso',
  apiTelefono: ' http://localhost:3000/api/telefono',
  apiProducto: ' http://localhost:3000/api/producto',
  apiRol: ' http://localhost:3000/api/rol',
  apiCategoria: 'http://localhost:3000/api/categoria',
  apiProductosPorPedido : 'http://localhost:3000/api/productos_por_venta'
};
