export const environment = {
  production: true,
  apiTipoCanal: 'https://masnutricionback.herokuapp.com/api/tipo-canal',
  apiTipoCliente: 'https://masnutricionback.herokuapp.com/api/tipo-cliente',
  apiTipoCondiciones: 'https://masnutricionback.herokuapp.com/api/tipo-condiciones',
  apiTipoFamilia: 'https://masnutricionback.herokuapp.com/api/tipo-familia',
  apiTipoIVA: 'https://masnutricionback.herokuapp.com/api/tipo-iva',
  apiTipoPermiso: 'https://masnutricionback.herokuapp.com/api/tipo-permiso',
  apiTipoProducto: 'https://masnutricionback.herokuapp.com/api/tipo-producto',
  apiTipoRegla: 'https://masnutricionback.herokuapp.com/api/tipo-reglaComercial',
  apiTipoTelefono: 'https://masnutricionback.herokuapp.com/api/tipo-telefono',
  apiUsuario: 'https://masnutricionback.herokuapp.com/api/usuario',
  apiCliente: 'https://masnutricionback.herokuapp.com/api/cliente',
  apiEmpresa: 'https://masnutricionback.herokuapp.com/api/empresa',
  apiVendedor: 'https://masnutricionback.herokuapp.com/api/vendedor',
  apiLocalidad: 'https://masnutricionback.herokuapp.com/api/localidad',
  apiProvincia: 'https://masnutricionback.herokuapp.com/api/provincia',
  apiPedido: 'https://masnutricionback.herokuapp.com/api/pedido',
  apiOperacion: 'https://masnutricionback.herokuapp.com/api/operacion',
  apiDetallePedido: 'https://masnutricionback.herokuapp.com/api/detallePedido',
  apiEmail:'https://masnutricionback.herokuapp.com/api/email',
  apiAccesoPermiso:'https://masnutricionback.herokuapp.com/api/accesoPermiso',
  apiAcceso:'https://masnutricionback.herokuapp.com/api/acceso',
  apiTelefono: 'https://masnutricionback.herokuapp.com/api/telefono',
  apiProducto: 'https://masnutricionback.herokuapp.com/api/producto',
  apiRol: 'https://masnutricionback.herokuapp.com/api/rol'
};
